services:
  mssql:
    container_name: 'lojinha_mssql'
    image: mcr.microsoft.com/mssql/server:latest
    env_file:
      - .env
    environment:
      SA_PASSWORD: '${MSSQL_SA_PASSWORD}'
      ACCEPT_EULA: 'Y'
    ports:
      - '${MSSQL_PORT}:1433'
    networks:
      - databases

networks:
  databases:
    name: 'lojinha_databases'
    driver: bridge
