services:
  mssql:
    container_name: 'lojinha_mssql'
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      SA_PASSWORD: 'Dev@123456'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
    networks:
      - databases

networks:
  databases:
    name: 'lojinha_databases'
    driver: bridge
