services:
  postgres:
    container_name: 'lojinha_postgres'
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - databases

networks:
  databases:
    name: 'lojinha_databases'
    driver: bridge
